version: '3.7'

services:
  sofi:
    restart: always
    build: '.'
    container_name: sofi
    depends_on:
      - cache
      - database
    ports:
      - 9090:9090
    cap_add:
      - LINUX_IMMUTABLE
      - CAP_SYS_ADMIN
  database:
    image: mongo:latest
      container_name: database
      restart: always
      volumes:
        - ./logs:/data/db
  cache:
    image: redis:7.0.5-alpine
    container_name: cache