version: '3.7'

services:
  sofi:
    restart: always
    build: '.'
    container_name: sofi
    depends_on:
      - cache
    ports:
      - 9090:9090
    cap_add:
      - LINUX_IMMUTABLE
  cache:
    image: redis:7.0.5-alpine
    container_name: cache